### ISSUE TITLE
How to manage BGRA8 image encoding 

### ISSUE THREAD

**Issue by lucarossini-iit** [leggedrobotics/elevation_mapping_cupy#96]
Hello guys and thanks for the amazing work! I am currently using the elevation mapping tool with a ZedX Mini camera that uses the BGRA8 encoding for the colored image. This is the config file I am currently using: 

``` yaml

#### Plugins ########
plugin_config_file: '$(rospack find elevation_mapping_cupy)/config/core/plugin_config.yaml'

#### Channel Fusions ########
pointcloud_channel_fusions:
  rgb: 'color'                # 'color' fusion is used for the 'rgb' channel
  default: 'average'          # 'average' fusion is used for channels not listed here

image_channel_fusions:
  rgb: 'color'                # 'color' fusion is used for the 'rgb' channel
  default: 'exponential'      # 'exponential' fusion is used for channels not listed here
  feat_.*: 'exponential'      # 'exponential' fusion is also used for any channel starting with 'feat_' Regular expressions can be used for channel names

subscribers:
  front_cam:
    topic_name: '/zedx_left/zed_node/point_cloud/cloud_registered'
    data_type: pointcloud
  color_cam: # for color camera
    topic_name: '/zedx_left/zed_node/rgb/image_rect_color'
    camera_info_topic_name: '/zedx_left/zed_node/rgb/camera_info'
    data_type: image

publishers:
  elevation_map_raw:
    layers: ['elevation', 'traversability', 'variance']
    basic_layers: ['elevation']
    fps: 5.0
  elevation_map_recordable:
   layers: ['elevation', 'traversability']
   basic_layers: ['elevation', 'traversability']
   fps: 2.0
  elevation_map_filter:
    layers: ['min_filter', 'smooth', 'inpaint', 'elevation']
    basic_layers: ['min_filter']
    fps: 3.0
```

However, when I run the code, it returns me the following error:

```
Mismatch in the size of multichannel_image (4), channels (1). Please check the input.
Current Channels: rgb
```

Digging in you code, it should support the bgra8 image encoding but I don't know how to fix this problem. Probably the issue is in the `rgb`field of the Channel Fusion section of the config file but I am not sure how the code will react by simply modifying the config file field. 

What should I do to use the elevation mapping with bgra8 endoded images?

Thank you very much.
Luca Rossini
